import Head from "next/head";
import { useState } from "react";
import LoginForm from "../components/LoginForm";
import RegisterForm from "../components/RegisterForm";
import Vault from "../components/Vault";


export default function Home() {
  const [step, setStep] = useState<"login" | "register" | "vault">("register");
  return (
    <>
      <Head>
        <title>Password cheeek</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {step === "register" && <RegisterForm />}
        {step === "login" && <LoginForm />}
        {step === "vault" && <Vault />}
      </main>
    </>
  );
}
